name: Build Android DDTO (Fix Faxe)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          
          # Configuração Global para evitar erros de Clone e Perguntas
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          
          # Bibliotecas Principais (Usando --always para aceitar dependências automaticamente)
          haxelib git lime https://github.com/haxelime/lime.git --always --quiet
          haxelib git openfl https://github.com/openfl/openfl.git --always --quiet
          haxelib git flixel https://github.com/HaxeFlixel/flixel.git --always --quiet
          
          # Bibliotecas Standard do Haxelib
          haxelib install flixel-tools --always --quiet
          haxelib install flixel-ui --always --quiet
          haxelib install flixel-addons --always --quiet
          haxelib install tjson --always --quiet
          haxelib install hxvlc --always --quiet
          haxelib install actuate --always --quiet
          
          # Bibliotecas Específicas via Git (Links de alta compatibilidade)
          haxelib git faxe https://github.com/Tandem-Yug/faxe.git --always --quiet
          haxelib git polymod https://github.com/larsiusprime/polymod.git --always --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --always --quiet
          haxelib git extension-androidtools https://github.com/MAJ0R-Z/extension-androidtools --always --quiet
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git --always --quiet
          haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git --always --quiet

      - name: Configure Android
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime setup android "${{ github.workspace }}" "${{ steps.setup-java.outputs.path }}" "$ANDROID_SDK_ROOT" "$ANDROID_NDK_LATEST_HOME"
          haxelib run lime config ANDROID_SDK $ANDROID_SDK_ROOT
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME

      - name: Build Android
        run: haxelib run lime build android -release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DDTO-Plus-Android-Build
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
          
